# Generated by Django 4.2.16 on 2024-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cooking_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('difficulty', models.CharField(max_length=50)),
                ('ingredients', models.TextField(help_text='List of ingredients')),
                ('categories', models.ManyToManyField(related_name='recipes', to='recipes.category')),
            ],
        ),
    ]
