# Generated by Django 4.2.16 on 2024-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default='recipes/no_picture.jpg', upload_to='recipes'),
        ),
    ]
